# Generated by Django 4.2.7 on 2024-01-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('cName', models.CharField(blank=True, max_length=100, null=True)),
                ('cEmail', models.CharField(max_length=100)),
                ('cUrl', models.CharField(max_length=50)),
                ('cAddress', models.CharField(max_length=100)),
                ('cPhno', models.CharField(max_length=100)),
            ],
        ),
    ]
