# Generated by Django 4.2.7 on 2024-01-30 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_app', '0002_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiledetail',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_app.employeecareer')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_app.employeeeucation')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_app.employeepersonal')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_app.register')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_app.salary')),
            ],
        ),
    ]
