# Generated by Django 4.2.7 on 2024-01-17 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee_app', '0002_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('stack_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=100)),
                ('stack_date', models.DateField(auto_now_add=True)),
                ('stack_quantity', models.PositiveIntegerField()),
                ('stack_location', models.CharField(max_length=100)),
                ('stack_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stack_notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_app.employeepersonal')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('production_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=100)),
                ('production_date', models.DateField(auto_now_add=True)),
                ('shift', models.CharField(max_length=50)),
                ('quantity_produced', models.PositiveIntegerField()),
                ('work_center', models.CharField(max_length=100)),
                ('production_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('production_status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee_app.employeepersonal')),
            ],
        ),
    ]
